#!/usr/bin/env python3

import jobrunner.api as jobrunner

if __name__ == "__main__":
    jobrunner.setup(["software/bittree", "software/amrex", "software/flashx"], verbose=True)
    jobrunner.clean(["tests"])
    jobrunner.setup(["tests"], verbose=True)
    jobrunner.submit(["tests"], verbose=True)
