#!/bin/bash

# Jobrunner commands
jobrunner setup software/bittree software/amrex software/flashx --verbose
jobrunner clean tests
jobrunner setup tests --verbose

# Run flashxtest
source config.sh
source enviornment.sh
cd tests
flashxtest run-suite --archive
