#!/bin/bash

# Some variables to be set
set -e
ulimit -S -c 1024000
ulimit -S -m 6144000
ulimit -S -v 6144000
umask 002

# Jobrunner commands
jobrunner setup software/bittree software/amrex software/flashx --verbose
jobrunner clean tests
jobrunner setup tests --verbose
jobrunner submit tests --verbose
